name: Strongtrond
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28834
title: Strongtrond
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#313131'
    - '#a1a1a1'
    - '#717171'
  brandStrength: 0.375
  lightness: 0.6276490255258977
  saturation: 0.625
  rhythmicContrast: 0.5136551395989954
purpose: []
