name: Strongtrond
favicon: null
layout_spectrum: 0.5837650981266052
typography_spectrum: 0.1859885163139552
title: Strongtrond
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4678817766252905
  lightness: 0.6276490255258977
  saturation: 0.9919756751041859
  rhythmicContrast: 0.5136551395989954
purpose: []
